// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWIc8Zyavk5IoACyEIqJw_Qra7GYcwSw',
    appId: '1:232806779781:web:c2cd984c7d8028f850d2ec',
    messagingSenderId: '232806779781',
    projectId: 'meridatech-8c677',
    authDomain: 'meridatech-8c677.firebaseapp.com',
    storageBucket: 'meridatech-8c677.appspot.com',
    measurementId: 'G-S3GBZEQ58Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZoKBKheYxewAoy8saKvsBl_m78AWRoI4',
    appId: '1:232806779781:android:ebb5e4adec898c5450d2ec',
    messagingSenderId: '232806779781',
    projectId: 'meridatech-8c677',
    storageBucket: 'meridatech-8c677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyjNaIbB6vPpNqYMpZy_suLmBiRVTWoE',
    appId: '1:232806779781:ios:bb1cd3669946bb6050d2ec',
    messagingSenderId: '232806779781',
    projectId: 'meridatech-8c677',
    storageBucket: 'meridatech-8c677.appspot.com',
    iosBundleId: 'com.example.meridatechAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYyjNaIbB6vPpNqYMpZy_suLmBiRVTWoE',
    appId: '1:232806779781:ios:bb1cd3669946bb6050d2ec',
    messagingSenderId: '232806779781',
    projectId: 'meridatech-8c677',
    storageBucket: 'meridatech-8c677.appspot.com',
    iosBundleId: 'com.example.meridatechAssessment',
  );
}
